name: proxy

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  test-proxy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ubuntu:latest
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: datadog/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
    steps:
      - uses: actions/checkout@v2
      - name: Clear tool cache
        run: rm -rf $RUNNER_TOOL_CACHE/*
      - name: Setup Java 11
        id: setup-java
        uses: ./
        with:
          java-version: 11
      - name: Verify Java 11
        run: __tests__/verify-java.sh 11 "${{ steps.setup-java.outputs.path }}" "${{ steps.setup-java.outputs.version }}"

  test-bypass-proxy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      https_proxy: http://no-such-proxy:3128
      no_proxy: api.adoptopenjdk.net,github.com,api.github.com,*.s3.amazonaws.com,s3.amazonaws.com
    steps:
      - uses: actions/checkout@v2
      - name: Clear tool cache
        run: rm -rf $RUNNER_TOOL_CACHE/*
      - name: Setup Java 11
        id: setup-java
        uses: ./
        with:
          java-version: 11
      - name: Verify Java 11
        run: __tests__/verify-java.sh 11 "${{ steps.setup-java.outputs.path }}" "${{ steps.setup-java.outputs.version }}"
